### REGISTER
POST http://localhost:8000/api/auth/register
content-type: application/json

{
    "email": "lee.dev@gmail.com",
    "password": "aA?12345",
    "first_name": "Lee",
    "last_name": "Dev",
    "phone_number": "+1-555-0101",
    "role": "admin",
    "department": "IT",
    "status": "active",
    "is_verified": true,
    "profile_pic": "https://t3.ftcdn.net/jpg/07/24/59/76/360_F_724597608_pmo5BsVumFcFyHJKlASG2Y2KpkkfiYUU.jpg"
}

### LOGIN
POST http://localhost:8000/api/auth/login
content-type: application/json

{
    "email": "lee.dev@gmail.com",
    "password": "aA?12345"
}

### TASKS
GET http://localhost:8000/api/tasks
content-type: application/json

### CUSTOMERS
GET http://localhost:8000/api/customers
content-type: application/json


### PRODUCTS
GET http://localhost:8000/api/products
content-type: application/json

### TicketCategory
GET http://localhost:8000/api/tickets/categories
content-type: application/json

{
    "name": "category - 7",
    "description": "desc - 7"
}


### TICKETS
GET http://localhost:8000/api/tickets
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4OThkOTc5NDNiM2ZiYTMxZjM0ZDY4ZCIsImVtYWlsIjoibGVlLmRldkBnbWFpbC5jb20iLCJwaG9uZSI6IisxLTU1NS0wMTAxIiwiZmlyc3RfbmFtZSI6IkxlZSIsImxhc3RfbmFtZSI6IkRldiIsInByb2ZpbGVfcGljIjoiaHR0cHM6Ly90My5mdGNkbi5uZXQvanBnLzA3LzI0LzU5Lzc2LzM2MF9GXzcyNDU5NzYwOF9wbW81QnNWdW1GY0Z5SEpLbEFTRzJZMktwa2tmaVlVVS5qcGciLCJ1c2VyX3R5cGUiOiJhZG1pbiIsImlzVmVyaWZpZWQiOnRydWUsImlhdCI6MTc1NDg0NzcyNywiZXhwIjoxNzU0OTM0MTI3fQ.T0bH09vy0DVYo1WSjjgopC5sBIPAZEzfvtLLrlvvNRg

{
    "customer": "6895c952fd8cdca80163a316",
    "caller_details": {
        "first_name": "test",
        "last_name": "testing",
        "email": "test@test.com",
        "phone_number": "+1-555-0101"
    },
    "title": "Test Ticket 2",
    "description": "This is a test 2 ticket",
    "category": "68972a25718db8f4eaa70141"

}
